using Availability.Application.Abstractions;
using Availability.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace Availability.Infrastructure.Persistence;

public class SlotRepository(ApplicationDbContext context) : ISlotRepository
{
    public const string StartIndexName = "IX_Slots_BranchId_ServiceTypeId_StartUtc";

    public const string LocalDateIndexName = "IX_Slots_BranchId_ServiceTypeId_LocalDate";

    public Task AddRangeAsync(IEnumerable<Slot> slots, CancellationToken cancellationToken)
    {
        return context.Slots.AddRangeAsync(slots, cancellationToken);
    }

    public Task<List<Slot>> ListOverlappingAsync(
        Guid branchId, Guid serviceTypeId, DateTime fromUtc, DateTime toUtc, CancellationToken cancellationToken)
    {
        return context.Slots
            .AsNoTracking()
            .Where(s => s.BranchId == branchId
                        && s.ServiceTypeId == serviceTypeId
                        && s.StartUtc < toUtc
                        && s.EndUtc > fromUtc)
            .ToListAsync(cancellationToken);
    }

    public Task<List<Slot>> SearchAvailableAsync(
        Guid branchId, Guid serviceTypeId, DateOnly localDate, DateTime afterUtc, CancellationToken cancellationToken)
    {
        return context.Slots
            .AsNoTracking()
            .Where(s => s.BranchId == branchId
                        && s.ServiceTypeId == serviceTypeId
                        && s.LocalDate == localDate
                        && s.StartUtc > afterUtc
                        && s.ReservedCount < s.Capacity)
            .OrderBy(s => s.StartUtc)
            .ToListAsync(cancellationToken);
    }

    public Task<Slot?> GetByIdAsync(Guid id, CancellationToken cancellationToken)
    {
        return context.Slots.AsNoTracking().FirstOrDefaultAsync(s => s.Id == id, cancellationToken);
    }

    public async Task SaveChangesAsync(CancellationToken cancellationToken)
    {
        try
        {
            await context.SaveChangesAsync(cancellationToken);
        }
        catch (DbUpdateException ex) when (UniqueViolation.IsOn(ex, StartIndexName))
        {
            throw new DuplicateSlotException(
                "Slots for this branch and service type were generated by a concurrent request.", ex);
        }
    }
}
