using SmartAppointments.BuildingBlocks.Models;

namespace Availability.Application.Handlers;

internal static class SlotErrors
{
    public static Error BranchInactive(string code) => new(409, $"Branch '{code}' is inactive.");

    public static Error ServiceTypeInactive(string code) => new(409, $"Service type '{code}' is inactive.");

    public static Error NoWorkingHours(string code) => new(409, $"Branch '{code}' has no working hours.");

    public static Error ConcurrentGeneration() => new(409,
        "Slots for this branch and service type were generated by a concurrent request. Try again.");
}
